function newMap()
  local map = { cities = {}, routes = {} }
  local x
  x = addCity(map, "Dyrrachium",byzantium,2,-23.28,15.11)
  x.mediterranean = true
  x = addCity(map, "Thessalonica",byzantium,3,-19.39,14.46)
  x.bulgarStart = true
  x.mediterranean = true
  x = addCity(map, "Athens",byzantium,2,-18.61,10.50)
  x = addCity(map, "Candia",byzantium,2,-16.55,5.75)
  x = addCity(map, "Adrianople",byzantium,2,-15.16,16.59)
  x.bulgarStart = true
  x = addCity(map, "Constantinople",byzantium,5,-11.80,15.83)
  x = addCity(map, "Nicea",byzantium,3,-9.10,14.60)
  x = addCity(map, "Smyrna",byzantium,2,-13.41,11.23)
  x = addCity(map, "Attalia",byzantium,2,-8.60,8.29)
  x = addCity(map, "Ankara",byzantium,2,-5.89,13.09)
  x = addCity(map, "Sinope",byzantium,2,-3.11,16.68)
  x.mediterranean = true
  x = addCity(map, "Trebizond",byzantium,2,2.35,15.67)
  x.mediterranean = true
  x = addCity(map, "Caesarea",byzantium,2,-1.68,11.98)
  x = addCity(map, "Tarsus",byzantium,2,-3.97,8.91)
  x = addCity(map, "Antioch",byzantium,2,-1.20,7.80)
  x = addCity(map, "Edessa",byzantium,2,1.59,8.85)
  x = addCity(map, "Damascus",byzantium,3,-1.44,3.12)
  x = addCity(map, "Jerusalem",byzantium,3,-2.59,0.36)
  -- x = addCity(map, "Alexandria",byzantium,3,-8.57,-0.54)
  x = addCity(map, "Alexandria",arabs,3,-8.57,-0.54)
  -- x = addCity(map, "Leucosia",byzantium,3,-5.66,5.37)
  x = addCity(map, "Leucosia",arabs,3,-5.66,5.37)
  x = addCity(map, "Palmyra",byzantium,3,3.35,4.91)
  x = addCity(map, "Tabuk",arabs,1,-1.58,-1.97)
  x = addCity(map, "Medina",arabs,1,2.47,-10.48)
  x = addCity(map, "Mecca",arabs,2,2.84,-14.87)
  x = addCity(map, "Basra",persians,3,13.64,-1.69)
  x = addCity(map, "Hira",persians,3,8.37,0.57)
  x = addCity(map, "Baghdad",persians,3,9.50,3.27)
  x = addCity(map, "Hamadan",persians,3,13.42,7.52)
  x = addCity(map, "Mosul",persians,3,6.58,9.00)
  x = addCity(map, "Amida",persians,2,3.72,11.04)
  x = addCity(map, "Ardabil",persians,2,14.74,11.92)
  x = addCity(map, "Tiflis",persians,2,9.15,16.38)
  x = addCity(map, "Derbent",persians,2,14.08,16.82)

  -- road
  addRoute(map, "Thessalonica", "Athens", road)
  addRoute(map, "Thessalonica", "Adrianople", road)
  addRoute(map, "Thessalonica", "Dyrrachium", road)
  addRoute(map, "Constantinople", "Adrianople", road)
  addRoute(map, "Nicea", "Smyrna", road)
  addRoute(map, "Nicea", "Ankara", road)
  addRoute(map, "Nicea", "Sinope", road)
  addRoute(map, "Smyrna", "Attalia", road)
  addRoute(map, "Attalia", "Ankara", road)
  addRoute(map, "Attalia", "Tarsus", road)
  addRoute(map, "Tarsus", "Ankara", road)
  addRoute(map, "Tarsus", "Antioch", road)
  addRoute(map, "Tarsus", "Caesarea", road)
  addRoute(map, "Antioch", "Edessa", road)
  addRoute(map, "Antioch", "Palmyra", road)
  addRoute(map, "Antioch", "Damascus", road)
  addRoute(map, "Damascus", "Palmyra", road)
  addRoute(map, "Damascus", "Jerusalem", road)
  addRoute(map, "Jerusalem", "Alexandria", road)
  addRoute(map, "Sinope", "Ankara", road)
  addRoute(map, "Sinope", "Trebizond", road)
  addRoute(map, "Trebizond", "Caesarea", road)
  addRoute(map, "Caesarea", "Ankara", road)

  addRoute(map, "Amida", "Trebizond", road)
  addRoute(map, "Amida", "Caesarea", road)
  addRoute(map, "Amida", "Edessa", road)
  addRoute(map, "Amida", "Mosul", road)
  addRoute(map, "Mosul", "Palmyra", road)
  addRoute(map, "Mosul", "Baghdad", road)
  addRoute(map, "Mosul", "Hamadan", road)
  addRoute(map, "Hamadan", "Baghdad", road)
  addRoute(map, "Hamadan", "Ardabil", road)
  addRoute(map, "Ardabil", "Derbent", road)
  addRoute(map, "Ardabil", "Tiflis", road)
  addRoute(map, "Tiflis", "Trebizond", road)
  addRoute(map, "Tiflis", "Derbent", road)
  addRoute(map, "Hira", "Palmyra", road)
  addRoute(map, "Hira", "Baghdad", road)
  addRoute(map, "Hira", "Basra", road)
  addRoute(map, "Basra", "Baghdad", road)

  -- desert
  addRoute(map,"Tabuk","Alexandria",desert)
  addRoute(map,"Tabuk","Jerusalem",desert)
  addRoute(map,"Tabuk","Medina",desert)
  addRoute(map,"Medina","Mecca",desert)
  addRoute(map,"Mecca","Hira",desert)
  addRoute(map,"Mecca","Basra",desert)

  -- sea
  addRoute(map,"Constantinople","Nicea",sea)
  addRoute(map,"Candia","Athens",sea)
  addRoute(map,"Candia","Smyrna",sea)
  addRoute(map,"Candia","Leucosia",sea)
  addRoute(map,"Candia","Alexandria",sea)
  addRoute(map,"Leucosia","Attalia",sea)
  addRoute(map,"Leucosia","Tarsus",sea)
  addRoute(map,"Leucosia","Antioch",sea)
  addRoute(map,"Leucosia","Damascus",sea)
  addRoute(map,"Leucosia","Alexandria",sea)

  return map
end

