var map = { nodes:
[{ node: 0, name: "Berlin-C\246lln", id: 0, vp: 0, priv: 2, req: "cube"}
,{ node: 1, name: "K\246nigsberg", id: 0, vp: 0, priv: 2, req: "cube"}
,{ node: 1, name: "K\246nigsberg", id: 1, vp: 0, priv: 4, req: "cube"}
,{ node: 2, name: "Belgard", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 3, name: "Halle", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 3, name: "Halle", id: 1, vp: 0, priv: 2, req: "disc"}
,{ node: 4, name: "Braunsberg", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 4, name: "Braunsberg", id: 1, vp: 0, priv: 2, req: "disc"}
,{ node: 5, name: "Tangerm\252nde", id: 0, vp: 0, priv: 2, req: "cube"}
,{ node: 6, name: "Elbing", id: 0, vp: 0, priv: 2, req: "cube"}
,{ node: 6, name: "Elbing", id: 1, vp: 0, priv: 4, req: "cube"}
,{ node: 7, name: "Frankfurt", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 7, name: "Frankfurt", id: 1, vp: 0, priv: 2, req: "cube"}
,{ node: 7, name: "Frankfurt", id: 2, vp: 0, priv: 3, req: "cube"}
,{ node: 8, name: "Allenstein", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 8, name: "Allenstein", id: 1, vp: 0, priv: 3, req: "cube"}
,{ node: 9, name: "Malm\246", id: 0, vp: 0, priv: 1, req: "disc"}
,{ node: 9, name: "Malm\246", id: 1, vp: 0, priv: 2, req: "cube"}
,{ node: 9, name: "Malm\246", id: 2, vp: 0, priv: 3, req: "disc"}
,{ node: 10, name: "Anklam", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 10, name: "Anklam", id: 1, vp: 0, priv: 3, req: "cube"}
,{ node: 11, name: "Stralsund", id: 0, vp: 0, priv: 2, req: "cube"}
,{ node: 11, name: "Stralsund", id: 1, vp: 0, priv: 2, req: "disc"}
,{ node: 12, name: "Perleberg", id: 0, vp: 0, priv: 2, req: "cube"}
,{ node: 13, name: "Visby", id: 0, vp: 0, priv: 2, req: "disc"}
,{ node: 14, name: "Kulm", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 14, name: "Kulm", id: 1, vp: 0, priv: 3, req: "cube"}
,{ node: 15, name: "Krakau", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 15, name: "Krakau", id: 1, vp: 0, priv: 3, req: "cube"}
,{ node: 15, name: "Krakau", id: 2, vp: 0, priv: 4, req: "cube"}
,{ node: 16, name: "Wismar", id: 0, vp: 0, priv: 2, req: "cube"}
,{ node: 16, name: "Wismar", id: 1, vp: 0, priv: 3, req: "disc"}
,{ node: 17, name: "Stettin", id: 0, vp: 0, priv: 2, req: "cube"}
,{ node: 17, name: "Stettin", id: 1, vp: 0, priv: 4, req: "cube"}
,{ node: 18, name: "Magdeburg", id: 0, vp: 1, priv: 1, req: "cube"}
,{ node: 18, name: "Magdeburg", id: 1, vp: 0, priv: 2, req: "cube"}
,{ node: 19, name: "Dresden", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 20, name: "Havelberg", id: 0, vp: 1, priv: 1, req: "cube"}
,{ node: 20, name: "Havelberg", id: 1, vp: 0, priv: 1, req: "disc"}
,{ node: 20, name: "Havelberg", id: 2, vp: 0, priv: 3, req: "cube"}
,{ node: 20, name: "Havelberg", id: 3, vp: 0, priv: 4, req: "cube"}
,{ node: 21, name: "Waren", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 22, name: "Breslau", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 22, name: "Breslau", id: 1, vp: 0, priv: 2, req: "disc"}
,{ node: 22, name: "Breslau", id: 2, vp: 0, priv: 4, req: "cube"}
,{ node: 23, name: "Thorn", id: 0, vp: 1, priv: 1, req: "cube"}
,{ node: 23, name: "Thorn", id: 1, vp: 0, priv: 2, req: "cube"}
,{ node: 23, name: "Thorn", id: 2, vp: 0, priv: 4, req: "cube"}
,{ node: 24, name: "Wittenberg", id: 0, vp: 0, priv: 3, req: "cube"}
,{ node: 25, name: "L\252beck", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 25, name: "L\252beck", id: 1, vp: 0, priv: 2, req: "cube"}
,{ node: 25, name: "L\252beck", id: 2, vp: 0, priv: 4, req: "cube"}
,{ node: 26, name: "Brandenburg", id: 0, vp: 0, priv: 1, req: "disc"}
,{ node: 26, name: "Brandenburg", id: 1, vp: 0, priv: 3, req: "cube"}
,{ node: 27, name: "Danzig", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 27, name: "Danzig", id: 1, vp: 0, priv: 2, req: "cube"}
,{ node: 27, name: "Danzig", id: 2, vp: 0, priv: 3, req: "cube"}
,{ node: 27, name: "Danzig", id: 3, vp: 0, priv: 4, req: "cube"}
]
, edges:
[{ edge: 0, from: "Krakau", to: "Thorn", spot: 0, req: "cube", prov: -1}
,{ edge: 0, from: "Krakau", to: "Thorn", spot: 1, req: "cube", prov: -1}
,{ edge: 0, from: "Krakau", to: "Thorn", spot: 2, req: "cube", prov: -1}
,{ edge: 1, from: "Krakau", to: "Breslau", spot: 0, req: "cube", prov: -1}
,{ edge: 1, from: "Krakau", to: "Breslau", spot: 1, req: "cube", prov: -1}
,{ edge: 1, from: "Krakau", to: "Breslau", spot: 2, req: "cube", prov: -1}
,{ edge: 2, from: "Allenstein", to: "Braunsberg", spot: 0, req: "cube", prov: -1}
,{ edge: 2, from: "Allenstein", to: "Braunsberg", spot: 1, req: "cube", prov: -1}
,{ edge: 2, from: "Allenstein", to: "Braunsberg", spot: 2, req: "cube", prov: -1}
,{ edge: 3, from: "Braunsberg", to: "Danzig", spot: 0, req: "cube", prov: -1}
,{ edge: 3, from: "Braunsberg", to: "Danzig", spot: 1, req: "cube", prov: -1}
,{ edge: 3, from: "Braunsberg", to: "Danzig", spot: 2, req: "cube", prov: -1}
,{ edge: 3, from: "Braunsberg", to: "Danzig", spot: 3, req: "cube", prov: -1}
,{ edge: 4, from: "Danzig", to: "K\246nigsberg", spot: 0, req: "cube", prov: -1}
,{ edge: 4, from: "Danzig", to: "K\246nigsberg", spot: 1, req: "cube", prov: -1}
,{ edge: 4, from: "Danzig", to: "K\246nigsberg", spot: 2, req: "cube", prov: -1}
,{ edge: 4, from: "Danzig", to: "K\246nigsberg", spot: 3, req: "cube", prov: -1}
,{ edge: 5, from: "Danzig", to: "Belgard", spot: 0, req: "cube", prov: -1}
,{ edge: 5, from: "Danzig", to: "Belgard", spot: 1, req: "cube", prov: -1}
,{ edge: 5, from: "Danzig", to: "Belgard", spot: 2, req: "cube", prov: -1}
,{ edge: 5, from: "Danzig", to: "Belgard", spot: 3, req: "cube", prov: -1}
,{ edge: 6, from: "Danzig", to: "Malm\246", spot: 0, req: "cube", prov: -1}
,{ edge: 6, from: "Danzig", to: "Malm\246", spot: 1, req: "cube", prov: -1}
,{ edge: 6, from: "Danzig", to: "Malm\246", spot: 2, req: "cube", prov: -1}
,{ edge: 6, from: "Danzig", to: "Malm\246", spot: 3, req: "disc", prov: -1}
,{ edge: 7, from: "Wismar", to: "L\252beck", spot: 0, req: "cube", prov: -1}
,{ edge: 7, from: "Wismar", to: "L\252beck", spot: 1, req: "cube", prov: -1}
,{ edge: 7, from: "Wismar", to: "L\252beck", spot: 2, req: "cube", prov: -1}
,{ edge: 8, from: "Wismar", to: "Stralsund", spot: 0, req: "cube", prov: -1}
,{ edge: 8, from: "Wismar", to: "Stralsund", spot: 1, req: "disc", prov: -1}
,{ edge: 8, from: "Wismar", to: "Stralsund", spot: 2, req: "disc", prov: -1}
,{ edge: 9, from: "Waren", to: "Wismar", spot: 0, req: "cube", prov: -1}
,{ edge: 9, from: "Waren", to: "Wismar", spot: 1, req: "cube", prov: -1}
,{ edge: 9, from: "Waren", to: "Wismar", spot: 2, req: "cube", prov: -1}
,{ edge: 10, from: "Waren", to: "Havelberg", spot: 0, req: "cube", prov: -1}
,{ edge: 10, from: "Waren", to: "Havelberg", spot: 1, req: "cube", prov: -1}
,{ edge: 10, from: "Waren", to: "Havelberg", spot: 2, req: "cube", prov: -1}
,{ edge: 11, from: "Havelberg", to: "Perleberg", spot: 0, req: "cube", prov: -1}
,{ edge: 11, from: "Havelberg", to: "Perleberg", spot: 1, req: "cube", prov: -1}
,{ edge: 12, from: "Brandenburg", to: "Tangerm\252nde", spot: 0, req: "cube", prov: -1}
,{ edge: 12, from: "Brandenburg", to: "Tangerm\252nde", spot: 1, req: "cube", prov: -1}
,{ edge: 13, from: "Brandenburg", to: "Berlin-C\246lln", spot: 0, req: "cube", prov: -1}
,{ edge: 13, from: "Brandenburg", to: "Berlin-C\246lln", spot: 1, req: "cube", prov: -1}
,{ edge: 13, from: "Brandenburg", to: "Berlin-C\246lln", spot: 2, req: "cube", prov: -1}
,{ edge: 14, from: "Brandenburg", to: "Stettin", spot: 0, req: "cube", prov: -1}
,{ edge: 14, from: "Brandenburg", to: "Stettin", spot: 1, req: "cube", prov: -1}
,{ edge: 14, from: "Brandenburg", to: "Stettin", spot: 2, req: "cube", prov: -1}
,{ edge: 15, from: "Magdeburg", to: "Halle", spot: 0, req: "cube", prov: -1}
,{ edge: 15, from: "Magdeburg", to: "Halle", spot: 1, req: "cube", prov: -1}
,{ edge: 15, from: "Magdeburg", to: "Halle", spot: 2, req: "cube", prov: -1}
,{ edge: 16, from: "Halle", to: "Wittenberg", spot: 0, req: "cube", prov: -1}
,{ edge: 16, from: "Halle", to: "Wittenberg", spot: 1, req: "cube", prov: -1}
,{ edge: 17, from: "Halle", to: "Dresden", spot: 0, req: "cube", prov: -1}
,{ edge: 17, from: "Halle", to: "Dresden", spot: 1, req: "cube", prov: -1}
,{ edge: 17, from: "Halle", to: "Dresden", spot: 2, req: "cube", prov: -1}
,{ edge: 17, from: "Halle", to: "Dresden", spot: 3, req: "cube", prov: -1}
,{ edge: 18, from: "Halle", to: "Brandenburg", spot: 0, req: "cube", prov: -1}
,{ edge: 18, from: "Halle", to: "Brandenburg", spot: 1, req: "cube", prov: -1}
,{ edge: 18, from: "Halle", to: "Brandenburg", spot: 2, req: "cube", prov: -1}
,{ edge: 19, from: "Dresden", to: "Krakau", spot: 0, req: "cube", prov: -1}
,{ edge: 19, from: "Dresden", to: "Krakau", spot: 1, req: "cube", prov: -1}
,{ edge: 19, from: "Dresden", to: "Krakau", spot: 2, req: "cube", prov: -1}
,{ edge: 19, from: "Dresden", to: "Krakau", spot: 3, req: "cube", prov: -1}
,{ edge: 20, from: "Breslau", to: "Frankfurt", spot: 0, req: "cube", prov: -1}
,{ edge: 20, from: "Breslau", to: "Frankfurt", spot: 1, req: "cube", prov: -1}
,{ edge: 20, from: "Breslau", to: "Frankfurt", spot: 2, req: "cube", prov: -1}
,{ edge: 21, from: "Frankfurt", to: "Stettin", spot: 0, req: "cube", prov: -1}
,{ edge: 21, from: "Frankfurt", to: "Stettin", spot: 1, req: "cube", prov: -1}
,{ edge: 22, from: "Stettin", to: "Kulm", spot: 0, req: "cube", prov: -1}
,{ edge: 22, from: "Stettin", to: "Kulm", spot: 1, req: "cube", prov: -1}
,{ edge: 22, from: "Stettin", to: "Kulm", spot: 2, req: "cube", prov: -1}
,{ edge: 23, from: "Stettin", to: "Anklam", spot: 0, req: "cube", prov: -1}
,{ edge: 23, from: "Stettin", to: "Anklam", spot: 1, req: "cube", prov: -1}
,{ edge: 23, from: "Stettin", to: "Anklam", spot: 2, req: "cube", prov: -1}
,{ edge: 24, from: "Stettin", to: "Waren", spot: 0, req: "cube", prov: -1}
,{ edge: 24, from: "Stettin", to: "Waren", spot: 1, req: "cube", prov: -1}
,{ edge: 24, from: "Stettin", to: "Waren", spot: 2, req: "cube", prov: -1}
,{ edge: 24, from: "Stettin", to: "Waren", spot: 3, req: "cube", prov: -1}
,{ edge: 25, from: "Thorn", to: "Allenstein", spot: 0, req: "cube", prov: -1}
,{ edge: 25, from: "Thorn", to: "Allenstein", spot: 1, req: "cube", prov: -1}
,{ edge: 25, from: "Thorn", to: "Allenstein", spot: 2, req: "cube", prov: -1}
,{ edge: 26, from: "Kulm", to: "Elbing", spot: 0, req: "cube", prov: -1}
,{ edge: 26, from: "Kulm", to: "Elbing", spot: 1, req: "cube", prov: -1}
,{ edge: 27, from: "Kulm", to: "Belgard", spot: 0, req: "cube", prov: -1}
,{ edge: 27, from: "Kulm", to: "Belgard", spot: 1, req: "cube", prov: -1}
,{ edge: 27, from: "Kulm", to: "Belgard", spot: 2, req: "cube", prov: -1}
,{ edge: 28, from: "Elbing", to: "Braunsberg", spot: 0, req: "cube", prov: -1}
,{ edge: 28, from: "Elbing", to: "Braunsberg", spot: 1, req: "cube", prov: -1}
,{ edge: 28, from: "Elbing", to: "Braunsberg", spot: 2, req: "cube", prov: -1}
,{ edge: 29, from: "Belgard", to: "Anklam", spot: 0, req: "cube", prov: -1}
,{ edge: 29, from: "Belgard", to: "Anklam", spot: 1, req: "cube", prov: -1}
,{ edge: 29, from: "Belgard", to: "Anklam", spot: 2, req: "cube", prov: -1}
,{ edge: 30, from: "Malm\246", to: "Visby", spot: 0, req: "cube", prov: -1}
,{ edge: 30, from: "Malm\246", to: "Visby", spot: 1, req: "disc", prov: -1}
,{ edge: 30, from: "Malm\246", to: "Visby", spot: 2, req: "cube", prov: -1}
,{ edge: 31, from: "Stralsund", to: "Malm\246", spot: 0, req: "cube", prov: -1}
,{ edge: 31, from: "Stralsund", to: "Malm\246", spot: 1, req: "disc", prov: -1}
,{ edge: 31, from: "Stralsund", to: "Malm\246", spot: 2, req: "disc", prov: -1}
]
}
