var map = { nodes:
[{ node: 0, name: "Magdeburg", id: 0, vp: 0, priv: 1, req: "disc"}
,{ node: 0, name: "Magdeburg", id: 1, vp: 0, priv: 2, req: "cube"}
,{ node: 1, name: "Stendal", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 1, name: "Stendal", id: 1, vp: 0, priv: 1, req: "disc"}
,{ node: 1, name: "Stendal", id: 2, vp: 0, priv: 2, req: "cube"}
,{ node: 1, name: "Stendal", id: 3, vp: 0, priv: 3, req: "cube"}
,{ node: 2, name: "Coellen", id: 0, vp: 1, priv: 1, req: "cube"}
,{ node: 2, name: "Coellen", id: 1, vp: 0, priv: 3, req: "cube"}
,{ node: 3, name: "L\252neburg", id: 0, vp: 0, priv: 2, req: "disc"}
,{ node: 3, name: "L\252neburg", id: 1, vp: 0, priv: 4, req: "cube"}
,{ node: 4, name: "Quedlinburg", id: 0, vp: 0, priv: 2, req: "disc"}
,{ node: 4, name: "Quedlinburg", id: 1, vp: 0, priv: 3, req: "disc"}
,{ node: 5, name: "Goslar", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 5, name: "Goslar", id: 1, vp: 0, priv: 4, req: "cube"}
,{ node: 6, name: "Halle", id: 0, vp: 1, priv: 1, req: "cube"}
,{ node: 6, name: "Halle", id: 1, vp: 0, priv: 2, req: "cube"}
,{ node: 7, name: "M\252nster", id: 0, vp: 0, priv: 1, req: "disc"}
,{ node: 7, name: "M\252nster", id: 1, vp: 0, priv: 2, req: "cube"}
,{ node: 8, name: "G\246ttingen", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 8, name: "G\246ttingen", id: 1, vp: 0, priv: 1, req: "disc"}
,{ node: 8, name: "G\246ttingen", id: 2, vp: 0, priv: 3, req: "cube"}
,{ node: 9, name: "Minden", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 9, name: "Minden", id: 1, vp: 0, priv: 2, req: "cube"}
,{ node: 9, name: "Minden", id: 2, vp: 0, priv: 3, req: "cube"}
,{ node: 9, name: "Minden", id: 3, vp: 0, priv: 4, req: "cube"}
,{ node: 10, name: "Stade", id: 0, vp: 0, priv: 1, req: "disc"}
,{ node: 11, name: "Arnheim", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 11, name: "Arnheim", id: 1, vp: 0, priv: 1, req: "disc"}
,{ node: 11, name: "Arnheim", id: 2, vp: 0, priv: 2, req: "cube"}
,{ node: 11, name: "Arnheim", id: 3, vp: 0, priv: 3, req: "cube"}
,{ node: 12, name: "Emden", id: 0, vp: 0, priv: 1, req: "disc"}
,{ node: 12, name: "Emden", id: 1, vp: 0, priv: 3, req: "cube"}
,{ node: 13, name: "Gr\246ningen", id: 0, vp: 1, priv: 1, req: "cube"}
,{ node: 13, name: "Gr\246ningen", id: 1, vp: 0, priv: 2, req: "disc"}
,{ node: 14, name: "Bremen", id: 0, vp: 0, priv: 1, req: "disc"}
,{ node: 14, name: "Bremen", id: 1, vp: 0, priv: 3, req: "cube"}
,{ node: 15, name: "Hildesheim", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 15, name: "Hildesheim", id: 1, vp: 0, priv: 4, req: "cube"}
,{ node: 16, name: "Kampen", id: 0, vp: 0, priv: 2, req: "disc"}
,{ node: 16, name: "Kampen", id: 1, vp: 0, priv: 4, req: "cube"}
,{ node: 17, name: "Dortmund", id: 0, vp: 0, priv: 1, req: "disc"}
,{ node: 17, name: "Dortmund", id: 1, vp: 0, priv: 2, req: "cube"}
,{ node: 17, name: "Dortmund", id: 2, vp: 0, priv: 3, req: "cube"}
,{ node: 18, name: "Perleberg", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 18, name: "Perleberg", id: 1, vp: 0, priv: 3, req: "cube"}
,{ node: 18, name: "Perleberg", id: 2, vp: 0, priv: 4, req: "disc"}
,{ node: 19, name: "Osnabr\252ck", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 19, name: "Osnabr\252ck", id: 1, vp: 0, priv: 2, req: "cube"}
,{ node: 19, name: "Osnabr\252ck", id: 2, vp: 0, priv: 4, req: "cube"}
,{ node: 20, name: "Brunswick", id: 0, vp: 0, priv: 2, req: "cube"}
,{ node: 21, name: "L\252beck", id: 0, vp: 1, priv: 1, req: "cube"}
,{ node: 21, name: "L\252beck", id: 1, vp: 0, priv: 3, req: "cube"}
,{ node: 22, name: "Paderborn", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 22, name: "Paderborn", id: 1, vp: 0, priv: 4, req: "disc"}
,{ node: 23, name: "Duisburg", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 24, name: "Hamburg", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 24, name: "Hamburg", id: 1, vp: 0, priv: 2, req: "cube"}
,{ node: 24, name: "Hamburg", id: 2, vp: 0, priv: 4, req: "cube"}
,{ node: 25, name: "Warburg", id: 0, vp: 0, priv: 2, req: "cube"}
,{ node: 25, name: "Warburg", id: 1, vp: 0, priv: 3, req: "cube"}
,{ node: 26, name: "Hannover", id: 0, vp: 0, priv: 1, req: "cube"}
,{ node: 26, name: "Hannover", id: 1, vp: 0, priv: 3, req: "cube"}
]
, edges:
[{ edge: 0, from: "Hamburg", to: "L\252beck", spot: 0, req: "cube", prov: -1}
,{ edge: 0, from: "Hamburg", to: "L\252beck", spot: 1, req: "cube", prov: -1}
,{ edge: 0, from: "Hamburg", to: "L\252beck", spot: 2, req: "cube", prov: -1}
,{ edge: 1, from: "Hamburg", to: "L\252neburg", spot: 0, req: "cube", prov: -1}
,{ edge: 1, from: "Hamburg", to: "L\252neburg", spot: 1, req: "cube", prov: -1}
,{ edge: 1, from: "Hamburg", to: "L\252neburg", spot: 2, req: "cube", prov: -1}
,{ edge: 1, from: "Hamburg", to: "L\252neburg", spot: 3, req: "cube", prov: -1}
,{ edge: 2, from: "Hamburg", to: "Bremen", spot: 0, req: "cube", prov: -1}
,{ edge: 2, from: "Hamburg", to: "Bremen", spot: 1, req: "cube", prov: -1}
,{ edge: 2, from: "Hamburg", to: "Bremen", spot: 2, req: "cube", prov: -1}
,{ edge: 2, from: "Hamburg", to: "Bremen", spot: 3, req: "cube", prov: -1}
,{ edge: 3, from: "Hamburg", to: "Stade", spot: 0, req: "cube", prov: -1}
,{ edge: 3, from: "Hamburg", to: "Stade", spot: 1, req: "cube", prov: -1}
,{ edge: 3, from: "Hamburg", to: "Stade", spot: 2, req: "cube", prov: -1}
,{ edge: 4, from: "Emden", to: "Gr\246ningen", spot: 0, req: "cube", prov: -1}
,{ edge: 4, from: "Emden", to: "Gr\246ningen", spot: 1, req: "cube", prov: -1}
,{ edge: 4, from: "Emden", to: "Gr\246ningen", spot: 2, req: "cube", prov: -1}
,{ edge: 5, from: "Emden", to: "Osnabr\252ck", spot: 0, req: "cube", prov: -1}
,{ edge: 5, from: "Emden", to: "Osnabr\252ck", spot: 1, req: "cube", prov: -1}
,{ edge: 5, from: "Emden", to: "Osnabr\252ck", spot: 2, req: "cube", prov: -1}
,{ edge: 5, from: "Emden", to: "Osnabr\252ck", spot: 3, req: "cube", prov: -1}
,{ edge: 6, from: "Emden", to: "Stade", spot: 0, req: "cube", prov: -1}
,{ edge: 6, from: "Emden", to: "Stade", spot: 1, req: "cube", prov: -1}
,{ edge: 6, from: "Emden", to: "Stade", spot: 2, req: "cube", prov: -1}
,{ edge: 7, from: "Kampen", to: "Osnabr\252ck", spot: 0, req: "cube", prov: -1}
,{ edge: 7, from: "Kampen", to: "Osnabr\252ck", spot: 1, req: "cube", prov: -1}
,{ edge: 8, from: "Bremen", to: "Osnabr\252ck", spot: 0, req: "cube", prov: -1}
,{ edge: 8, from: "Bremen", to: "Osnabr\252ck", spot: 1, req: "cube", prov: -1}
,{ edge: 8, from: "Bremen", to: "Osnabr\252ck", spot: 2, req: "cube", prov: -1}
,{ edge: 9, from: "Bremen", to: "Minden", spot: 0, req: "cube", prov: -1}
,{ edge: 9, from: "Bremen", to: "Minden", spot: 1, req: "cube", prov: -1}
,{ edge: 9, from: "Bremen", to: "Minden", spot: 2, req: "cube", prov: -1}
,{ edge: 10, from: "Bremen", to: "Hannover", spot: 0, req: "cube", prov: -1}
,{ edge: 10, from: "Bremen", to: "Hannover", spot: 1, req: "cube", prov: -1}
,{ edge: 10, from: "Bremen", to: "Hannover", spot: 2, req: "cube", prov: -1}
,{ edge: 11, from: "Minden", to: "Hannover", spot: 0, req: "cube", prov: -1}
,{ edge: 11, from: "Minden", to: "Hannover", spot: 1, req: "cube", prov: -1}
,{ edge: 11, from: "Minden", to: "Hannover", spot: 2, req: "cube", prov: -1}
,{ edge: 12, from: "Minden", to: "Brunswick", spot: 0, req: "cube", prov: -1}
,{ edge: 12, from: "Minden", to: "Brunswick", spot: 1, req: "cube", prov: -1}
,{ edge: 12, from: "Minden", to: "Brunswick", spot: 2, req: "cube", prov: -1}
,{ edge: 12, from: "Minden", to: "Brunswick", spot: 3, req: "cube", prov: -1}
,{ edge: 13, from: "Minden", to: "Paderborn", spot: 0, req: "cube", prov: -1}
,{ edge: 13, from: "Minden", to: "Paderborn", spot: 1, req: "cube", prov: -1}
,{ edge: 13, from: "Minden", to: "Paderborn", spot: 2, req: "cube", prov: -1}
,{ edge: 14, from: "Minden", to: "M\252nster", spot: 0, req: "cube", prov: -1}
,{ edge: 14, from: "Minden", to: "M\252nster", spot: 1, req: "cube", prov: -1}
,{ edge: 14, from: "Minden", to: "M\252nster", spot: 2, req: "cube", prov: -1}
,{ edge: 15, from: "Arnheim", to: "Kampen", spot: 0, req: "cube", prov: -1}
,{ edge: 15, from: "Arnheim", to: "Kampen", spot: 1, req: "cube", prov: -1}
,{ edge: 15, from: "Arnheim", to: "Kampen", spot: 2, req: "cube", prov: -1}
,{ edge: 16, from: "Arnheim", to: "M\252nster", spot: 0, req: "cube", prov: -1}
,{ edge: 16, from: "Arnheim", to: "M\252nster", spot: 1, req: "cube", prov: -1}
,{ edge: 16, from: "Arnheim", to: "M\252nster", spot: 2, req: "cube", prov: -1}
,{ edge: 17, from: "Arnheim", to: "Duisburg", spot: 0, req: "cube", prov: -1}
,{ edge: 17, from: "Arnheim", to: "Duisburg", spot: 1, req: "cube", prov: -1}
,{ edge: 17, from: "Arnheim", to: "Duisburg", spot: 2, req: "cube", prov: -1}
,{ edge: 18, from: "Duisburg", to: "Dortmund", spot: 0, req: "cube", prov: -1}
,{ edge: 18, from: "Duisburg", to: "Dortmund", spot: 1, req: "cube", prov: -1}
,{ edge: 19, from: "Paderborn", to: "Dortmund", spot: 0, req: "cube", prov: -1}
,{ edge: 19, from: "Paderborn", to: "Dortmund", spot: 1, req: "cube", prov: -1}
,{ edge: 19, from: "Paderborn", to: "Dortmund", spot: 2, req: "cube", prov: -1}
,{ edge: 20, from: "Paderborn", to: "Warburg", spot: 0, req: "cube", prov: -1}
,{ edge: 20, from: "Paderborn", to: "Warburg", spot: 1, req: "cube", prov: -1}
,{ edge: 20, from: "Paderborn", to: "Warburg", spot: 2, req: "cube", prov: -1}
,{ edge: 21, from: "Paderborn", to: "Hildesheim", spot: 0, req: "cube", prov: -1}
,{ edge: 21, from: "Paderborn", to: "Hildesheim", spot: 1, req: "cube", prov: -1}
,{ edge: 21, from: "Paderborn", to: "Hildesheim", spot: 2, req: "cube", prov: -1}
,{ edge: 22, from: "L\252neburg", to: "Hannover", spot: 0, req: "cube", prov: -1}
,{ edge: 22, from: "L\252neburg", to: "Hannover", spot: 1, req: "cube", prov: -1}
,{ edge: 22, from: "L\252neburg", to: "Hannover", spot: 2, req: "cube", prov: -1}
,{ edge: 23, from: "L\252neburg", to: "Perleberg", spot: 0, req: "cube", prov: -1}
,{ edge: 23, from: "L\252neburg", to: "Perleberg", spot: 1, req: "cube", prov: -1}
,{ edge: 23, from: "L\252neburg", to: "Perleberg", spot: 2, req: "cube", prov: -1}
,{ edge: 24, from: "Stendal", to: "Perleberg", spot: 0, req: "cube", prov: -1}
,{ edge: 24, from: "Stendal", to: "Perleberg", spot: 1, req: "cube", prov: -1}
,{ edge: 24, from: "Stendal", to: "Perleberg", spot: 2, req: "cube", prov: -1}
,{ edge: 25, from: "Stendal", to: "Magdeburg", spot: 0, req: "cube", prov: -1}
,{ edge: 25, from: "Stendal", to: "Magdeburg", spot: 1, req: "cube", prov: -1}
,{ edge: 25, from: "Stendal", to: "Magdeburg", spot: 2, req: "cube", prov: -1}
,{ edge: 26, from: "Stendal", to: "Brunswick", spot: 0, req: "cube", prov: -1}
,{ edge: 26, from: "Stendal", to: "Brunswick", spot: 1, req: "cube", prov: -1}
,{ edge: 26, from: "Stendal", to: "Brunswick", spot: 2, req: "cube", prov: -1}
,{ edge: 26, from: "Stendal", to: "Brunswick", spot: 3, req: "cube", prov: -1}
,{ edge: 27, from: "Warburg", to: "Coellen", spot: 0, req: "cube", prov: -1}
,{ edge: 27, from: "Warburg", to: "Coellen", spot: 1, req: "cube", prov: -1}
,{ edge: 27, from: "Warburg", to: "Coellen", spot: 2, req: "cube", prov: -1}
,{ edge: 27, from: "Warburg", to: "Coellen", spot: 3, req: "cube", prov: -1}
,{ edge: 28, from: "Warburg", to: "G\246ttingen", spot: 0, req: "cube", prov: -1}
,{ edge: 28, from: "Warburg", to: "G\246ttingen", spot: 1, req: "cube", prov: -1}
,{ edge: 28, from: "Warburg", to: "G\246ttingen", spot: 2, req: "cube", prov: -1}
,{ edge: 29, from: "Quedlinburg", to: "G\246ttingen", spot: 0, req: "cube", prov: -1}
,{ edge: 29, from: "Quedlinburg", to: "G\246ttingen", spot: 1, req: "cube", prov: -1}
,{ edge: 29, from: "Quedlinburg", to: "G\246ttingen", spot: 2, req: "cube", prov: -1}
,{ edge: 30, from: "Quedlinburg", to: "Halle", spot: 0, req: "cube", prov: -1}
,{ edge: 30, from: "Quedlinburg", to: "Halle", spot: 1, req: "cube", prov: -1}
,{ edge: 30, from: "Quedlinburg", to: "Halle", spot: 2, req: "cube", prov: -1}
,{ edge: 30, from: "Quedlinburg", to: "Halle", spot: 3, req: "cube", prov: -1}
,{ edge: 31, from: "Quedlinburg", to: "Goslar", spot: 0, req: "cube", prov: -1}
,{ edge: 31, from: "Quedlinburg", to: "Goslar", spot: 1, req: "cube", prov: -1}
,{ edge: 31, from: "Quedlinburg", to: "Goslar", spot: 2, req: "cube", prov: -1}
,{ edge: 31, from: "Quedlinburg", to: "Goslar", spot: 3, req: "cube", prov: -1}
,{ edge: 32, from: "Goslar", to: "Magdeburg", spot: 0, req: "cube", prov: -1}
,{ edge: 32, from: "Goslar", to: "Magdeburg", spot: 1, req: "cube", prov: -1}
,{ edge: 33, from: "Goslar", to: "Hildesheim", spot: 0, req: "cube", prov: -1}
,{ edge: 33, from: "Goslar", to: "Hildesheim", spot: 1, req: "cube", prov: -1}
,{ edge: 33, from: "Goslar", to: "Hildesheim", spot: 2, req: "cube", prov: -1}
]
}
