

function mapUSA()
  local map = newMap()

  local function blackCity(r,c)
    local spot = newSpot(terrainCity)
    spot.trainLimit = 2
    spot.mayStart["Black"] = true
    spot.passenger = true
    spot.url = black_city_url
    locMapInsert(map.locations,location(r,c),spot)
  end

  local function mapLoc(r,c,t)
    if t == terrainCity then blackCity(r,c); return end
    local spot = newSpot(t)
    spot.trainLimit = 2
    if t == terrainPlains then spot.url = plains_url
    elseif t == terrainMountains then spot.url = mountains_url
    end
    locMapInsert(map.locations,location(r,c),spot)
  end

  local function eastCity(r,c)
    local spot = newSpot(terrainCity)
    spot.trainLimit = 1
    spot.railroadLimit = startingCity
    for _,c in ipairs({"Blue","Red","Orange","Black"}) do
      spot.mayStart[c] = true
    end
    spot.passenger = true
    spot.url = east_city_url
    locMapInsert(map.locations,location(r,c),spot)
  end

  local function westCity(r,c)
    local spot = newSpot(terrainCity)
    spot.trainLimit = 2
    for _,c in ipairs({"Purple","Black"}) do
      spot.mayStart[c] = true
    end
    spot.passenger = true
    spot.url = west_city_url
    locMapInsert(map.locations,location(r,c),spot)
  end

  local function chicago(r,c)
    local spot = newSpot(terrainCity)
    spot.trainLimit = 6
    for _,c in ipairs({"Orange","Yellow","Black"}) do
      spot.mayStart[c] = true
    end
    spot.bonusType  = bonusRecurring
    spot.bonus      = 2
    spot.passenger  = true
    spot.url        = big_city_url
    locMapInsert(map.locations,location(r,c),spot)
  end

  local function bonusBlackCity(r,c)
    local spot = newSpot(terrainCity)
    spot.trainLimit = 2
    spot.mayStart["Black"] = true
    spot.passenger  = true
    spot.bonusType  = bonusOnlyFirst
    spot.bonus      = 5
    spot.url        = black_bonus_city_url
    locMapInsert(map.locations,location(r,c),spot)
  end






  mapLoc(7, 9, terrainMountains)
  mapLoc(5, 9, terrainMountains)
  mapLoc(4, 9, terrainMountains)
  mapLoc(4, 8, terrainMountains)
  mapLoc(3, 8, terrainMountains)
  mapLoc(2, 8, terrainMountains)
  mapLoc(1, 8, terrainMountains)
  mapLoc(0, 8, terrainMountains)
  mapLoc(-1, 8, terrainMountains)
  mapLoc(0, 7, terrainMountains)
  mapLoc(1, 7, terrainMountains)
  mapLoc(0, 1, terrainMountains)
  mapLoc(1, 0, terrainMountains)
  mapLoc(0, 0, terrainMountains)
  mapLoc(-1, -11, terrainMountains)
  mapLoc(0, -12, terrainMountains)
  mapLoc(1, -13, terrainMountains)
  mapLoc(2, -14, terrainMountains)
  mapLoc(2, -15, terrainMountains)
  mapLoc(3, -16, terrainMountains)
  mapLoc(4, -16, terrainMountains)
  mapLoc(5, -17, terrainMountains)
  mapLoc(6, -17, terrainMountains)
  mapLoc(7, -18, terrainMountains)
  mapLoc(8, -18, terrainMountains)
  mapLoc(9, -19, terrainMountains)
  mapLoc(10, -19, terrainMountains)
  mapLoc(10, -15, terrainMountains)
  mapLoc(9, -15, terrainMountains)
  mapLoc(8, -15, terrainMountains)
  mapLoc(8, -14, terrainMountains)
  mapLoc(9, -14, terrainMountains)
  mapLoc(8, -13, terrainMountains)
  mapLoc(7, -13, terrainMountains)
  mapLoc(7, -12, terrainMountains)
  mapLoc(7, -11, terrainMountains)
  mapLoc(6, -11, terrainMountains)
  mapLoc(4, -9, terrainMountains)
  mapLoc(3, -8, terrainMountains)
  mapLoc(2, -8, terrainMountains)
  mapLoc(1, -7, terrainMountains)
  mapLoc(0, -7, terrainMountains)
  mapLoc(1, -8, terrainMountains)
  mapLoc(2, -9, terrainMountains)
  mapLoc(3, -9, terrainMountains)
  mapLoc(1, -9, terrainMountains)
  mapLoc(0, -8, terrainMountains)
  mapLoc(-1, -8, terrainMountains)
  mapLoc(-2, -8, terrainMountains)
  westCity(1, -15)
  westCity(8, -19)
  westCity(10, -20)
  mapLoc(10, -17, terrainCity)
  mapLoc(6, -15, terrainCity)
  mapLoc(3, -15, terrainCity)
  westCity(-2, -11)
  mapLoc(0, -10, terrainCity)
  mapLoc(4, -11, terrainCity)
  mapLoc(6, -12, terrainCity)
  mapLoc(9, -13, terrainCity)
  mapLoc(10, -11, terrainCity)
  mapLoc(9, -8, terrainCity)
  mapLoc(10, -6, terrainCity)
  mapLoc(7, -8, terrainCity)
  mapLoc(5, -8, terrainCity)
  bonusBlackCity(2, -7, terrainCity)
  mapLoc(-1, -6, terrainCity)
  mapLoc(-3, -7, terrainCity)
  mapLoc(-4, -3, terrainCity)
  mapLoc(-7, 2, terrainCity)
  mapLoc(-5, 3, terrainCity)
  bonusBlackCity(-3, 0, terrainCity)
  mapLoc(0, -2, terrainCity)
  bonusBlackCity(2, -2, terrainCity)
  mapLoc(5, -4, terrainCity)
  bonusBlackCity(8, -3)
  mapLoc(9, 0, terrainCity)
  mapLoc(7, 0, terrainCity)
  mapLoc(5, -1, terrainCity)
  mapLoc(2, 1, terrainCity)
  mapLoc(-1, 2, terrainCity)
  mapLoc(-5, 6, terrainCity)
  mapLoc(-6, 10, terrainCity)
  mapLoc(-8, 12, terrainCity)
  eastCity(-4, 10)
  mapLoc(-2, 7, terrainCity)
  mapLoc(0, 4, terrainCity)
  mapLoc(2, 5, terrainCity)
  chicago(5, 2)
  mapLoc(6, 4, terrainCity)
  mapLoc(6, 6, terrainCity)
  mapLoc(3, 7, terrainCity)
  eastCity(-2, 10)
  eastCity(-1, 11)
  eastCity(1, 10)
  eastCity(3, 10)
  eastCity(4, 11)
  mapLoc(6, 9, terrainCity)
  mapLoc(6, 11, terrainCity)
  mapLoc(8, 11, terrainCity)
  mapLoc(-7, 12, terrainPlains)
  mapLoc(-7, 11, terrainPlains)
  mapLoc(-6, 11, terrainPlains)
  mapLoc(-5, 10, terrainPlains)
  mapLoc(-5, 9, terrainPlains)
  mapLoc(-4, 9, terrainPlains)
  mapLoc(-3, 9, terrainPlains)
  mapLoc(-3, 10, terrainPlains)
  mapLoc(-4, 8, terrainPlains)
  mapLoc(-3, 8, terrainPlains)
  mapLoc(-2, 8, terrainPlains)
  mapLoc(-2, 9, terrainPlains)
  mapLoc(-1, 9, terrainPlains)
  mapLoc(-1, 10, terrainPlains)
  mapLoc(0, 10, terrainPlains)
  mapLoc(0, 11, terrainPlains)
  mapLoc(0, 9, terrainPlains)
  mapLoc(1, 9, terrainPlains)
  mapLoc(2, 9, terrainPlains)
  mapLoc(3, 9, terrainPlains)
  mapLoc(2, 10, terrainPlains)
  mapLoc(4, 10, terrainPlains)
  mapLoc(5, 8, terrainPlains)
  mapLoc(5, 10, terrainPlains)
  mapLoc(5, 11, terrainPlains)
  mapLoc(5, 12, terrainPlains)
  mapLoc(6, 10, terrainPlains)
  mapLoc(7, 10, terrainPlains)
  mapLoc(8, 10, terrainPlains)
  mapLoc(9, 10, terrainPlains)
  mapLoc(10, 10, terrainPlains)
  mapLoc(8, 9, terrainPlains)
  mapLoc(8, 8, terrainPlains)
  mapLoc(7, 8, terrainPlains)
  mapLoc(6, 8, terrainPlains)
  mapLoc(6, 7, terrainPlains)
  mapLoc(5, 7, terrainPlains)
  mapLoc(4, 7, terrainPlains)
  mapLoc(4, 6, terrainPlains)
  mapLoc(3, 6, terrainPlains)
  mapLoc(2, 7, terrainPlains)
  mapLoc(-4, 7, terrainPlains)
  mapLoc(-3, 7, terrainPlains)
  mapLoc(-4, 6, terrainPlains)
  mapLoc(-3, 6, terrainPlains)
  mapLoc(-2, 6, terrainPlains)
  mapLoc(-1, 6, terrainPlains)
  mapLoc(-1, 7, terrainPlains)
  mapLoc(0, 6, terrainPlains)
  mapLoc(1, 6, terrainPlains)
  mapLoc(2, 6, terrainPlains)
  mapLoc(4, 4, terrainPlains)
  mapLoc(4, 5, terrainPlains)
  mapLoc(3, 5, terrainPlains)
  mapLoc(5, 4, terrainPlains)
  mapLoc(6, 3, terrainPlains)
  mapLoc(7, 2, terrainPlains)
  mapLoc(8, 2, terrainPlains)
  mapLoc(7, 3, terrainPlains)
  mapLoc(5, 3, terrainPlains)
  mapLoc(4, 3, terrainPlains)
  mapLoc(3, 4, terrainPlains)
  mapLoc(2, 4, terrainPlains)
  mapLoc(1, 5, terrainPlains)
  mapLoc(0, 5, terrainPlains)
  mapLoc(-1, 5, terrainPlains)
  mapLoc(-2, 5, terrainPlains)
  mapLoc(-3, 5, terrainPlains)
  mapLoc(-4, 5, terrainPlains)
  mapLoc(-4, 4, terrainPlains)
  mapLoc(-4, 3, terrainPlains)
  mapLoc(-4, 2, terrainPlains)
  mapLoc(-5, 2, terrainPlains)
  mapLoc(-6, 2, terrainPlains)
  mapLoc(-6, 1, terrainPlains)
  mapLoc(-5, 1, terrainPlains)
  mapLoc(-4, 1, terrainPlains)
  mapLoc(-3, 1, terrainPlains)
  mapLoc(-3, 2, terrainPlains)
  mapLoc(-3, 3, terrainPlains)
  mapLoc(-3, 4, terrainPlains)
  mapLoc(-2, 4, terrainPlains)
  mapLoc(-1, 4, terrainPlains)
  mapLoc(1, 4, terrainPlains)
  mapLoc(2, 3, terrainPlains)
  mapLoc(4, 2, terrainPlains)
  mapLoc(3, 3, terrainPlains)
  mapLoc(3, 2, terrainPlains)
  mapLoc(4, 1, terrainPlains)
  mapLoc(5, 1, terrainPlains)
  mapLoc(6, 1, terrainPlains)
  mapLoc(6, 0, terrainPlains)
  mapLoc(8, -1, terrainPlains)
  mapLoc(9, -1, terrainPlains)
  mapLoc(8, 0, terrainPlains)
  mapLoc(7, -1, terrainPlains)
  mapLoc(8, -2, terrainPlains)
  mapLoc(9, -3, terrainPlains)
  mapLoc(10, -4, terrainPlains)
  mapLoc(10, -3, terrainPlains)
  mapLoc(9, -2, terrainPlains)
  mapLoc(-5, 0, terrainPlains)
  mapLoc(-5, -1, terrainPlains)
  mapLoc(-5, -2, terrainPlains)
  mapLoc(-4, -2, terrainPlains)
  mapLoc(-4, -1, terrainPlains)
  mapLoc(-4, 0, terrainPlains)
  mapLoc(-3, -1, terrainPlains)
  mapLoc(-2, -1, terrainPlains)
  mapLoc(-2, 0, terrainPlains)
  mapLoc(-2, 1, terrainPlains)
  mapLoc(-2, 2, terrainPlains)
  mapLoc(-2, 3, terrainPlains)
  mapLoc(-1, 3, terrainPlains)
  mapLoc(0, 2, terrainPlains)
  mapLoc(0, 3, terrainPlains)
  mapLoc(1, 2, terrainPlains)
  mapLoc(1, 1, terrainPlains)
  mapLoc(2, 0, terrainPlains)
  mapLoc(2, 2, terrainPlains)
  mapLoc(1, 3, terrainPlains)
  mapLoc(3, 1, terrainPlains)
  mapLoc(3, 0, terrainPlains)
  mapLoc(4, 0, terrainPlains)
  mapLoc(5, 0, terrainPlains)
  mapLoc(6, -1, terrainPlains)
  mapLoc(7, -2, terrainPlains)
  mapLoc(7, -3, terrainPlains)
  mapLoc(8, -4, terrainPlains)
  mapLoc(9, -5, terrainPlains)
  mapLoc(10, -5, terrainPlains)
  mapLoc(9, -4, terrainPlains)
  mapLoc(6, -2, terrainPlains)
  mapLoc(6, -3, terrainPlains)
  mapLoc(4, -1, terrainPlains)
  mapLoc(3, -1, terrainPlains)
  mapLoc(2, -1, terrainPlains)
  mapLoc(1, -1, terrainPlains)
  mapLoc(0, -1, terrainPlains)
  mapLoc(-1, -1, terrainPlains)
  mapLoc(-1, 1, terrainPlains)
  mapLoc(-1, 0, terrainPlains)
  mapLoc(-4, -4, terrainPlains)
  mapLoc(-4, -5, terrainPlains)
  mapLoc(-4, -6, terrainPlains)
  mapLoc(-3, -6, terrainPlains)
  mapLoc(-3, -5, terrainPlains)
  mapLoc(-2, -7, terrainPlains)
  mapLoc(-1, -7, terrainPlains)
  mapLoc(-3, -2, terrainPlains)
  mapLoc(-3, -4, terrainPlains)
  mapLoc(-2, -6, terrainPlains)
  mapLoc(-2, -5, terrainPlains)
  mapLoc(-3, -3, terrainPlains)
  mapLoc(-2, -4, terrainPlains)
  mapLoc(-1, -5, terrainPlains)
  mapLoc(0, -6, terrainPlains)
  mapLoc(-2, -3, terrainPlains)
  mapLoc(-2, -2, terrainPlains)
  mapLoc(-1, -2, terrainPlains)
  mapLoc(-1, -3, terrainPlains)
  mapLoc(-1, -4, terrainPlains)
  mapLoc(0, -5, terrainPlains)
  mapLoc(1, -6, terrainPlains)
  mapLoc(1, -5, terrainPlains)
  mapLoc(0, -4, terrainPlains)
  mapLoc(0, -3, terrainPlains)
  mapLoc(1, -4, terrainPlains)
  mapLoc(1, -3, terrainPlains)
  mapLoc(1, -2, terrainPlains)
  mapLoc(2, -3, terrainPlains)
  mapLoc(3, -3, terrainPlains)
  mapLoc(3, -2, terrainPlains)
  mapLoc(4, -2, terrainPlains)
  mapLoc(5, -2, terrainPlains)
  mapLoc(5, -3, terrainPlains)
  mapLoc(6, -4, terrainPlains)
  mapLoc(7, -4, terrainPlains)
  mapLoc(8, -5, terrainPlains)
  mapLoc(9, -6, terrainPlains)
  mapLoc(10, -7, terrainPlains)
  mapLoc(10, -8, terrainPlains)
  mapLoc(9, -7, terrainPlains)
  mapLoc(8, -6, terrainPlains)
  mapLoc(7, -5, terrainPlains)
  mapLoc(4, -3, terrainPlains)
  mapLoc(4, -4, terrainPlains)
  mapLoc(5, -5, terrainPlains)
  mapLoc(6, -5, terrainPlains)
  mapLoc(7, -6, terrainPlains)
  mapLoc(8, -7, terrainPlains)
  mapLoc(8, -8, terrainPlains)
  mapLoc(9, -9, terrainPlains)
  mapLoc(10, -9, terrainPlains)
  mapLoc(10, -10, terrainPlains)
  mapLoc(9, -10, terrainPlains)
  mapLoc(8, -9, terrainPlains)
  mapLoc(7, -7, terrainPlains)
  mapLoc(6, -6, terrainPlains)
  mapLoc(5, -6, terrainPlains)
  mapLoc(4, -5, terrainPlains)
  mapLoc(3, -4, terrainPlains)
  mapLoc(2, -4, terrainPlains)
  mapLoc(2, -5, terrainPlains)
  mapLoc(2, -6, terrainPlains)
  mapLoc(3, -7, terrainPlains)
  mapLoc(4, -8, terrainPlains)
  mapLoc(4, -7, terrainPlains)
  mapLoc(3, -6, terrainPlains)
  mapLoc(3, -5, terrainPlains)
  mapLoc(4, -6, terrainPlains)
  mapLoc(5, -7, terrainPlains)
  mapLoc(6, -7, terrainPlains)
  mapLoc(6, -8, terrainPlains)
  mapLoc(7, -9, terrainPlains)
  mapLoc(8, -10, terrainPlains)
  mapLoc(9, -11, terrainPlains)
  mapLoc(10, -12, terrainPlains)
  mapLoc(10, -13, terrainPlains)
  mapLoc(10, -14, terrainPlains)
  mapLoc(9, -12, terrainPlains)
  mapLoc(8, -12, terrainPlains)
  mapLoc(8, -11, terrainPlains)
  mapLoc(7, -10, terrainPlains)
  mapLoc(6, -9, terrainPlains)
  mapLoc(5, -9, terrainPlains)
  mapLoc(6, -10, terrainPlains)
  mapLoc(5, -10, terrainPlains)
  mapLoc(4, -10, terrainPlains)
  mapLoc(5, -11, terrainPlains)
  mapLoc(9, -20, terrainPlains)
  mapLoc(7, -19, terrainPlains)
  mapLoc(6, -18, terrainPlains)
  mapLoc(5, -18, terrainPlains)
  mapLoc(4, -17, terrainPlains)
  mapLoc(3, -17, terrainPlains)
  mapLoc(2, -16, terrainPlains)
  mapLoc(0, -14, terrainPlains)
  mapLoc(1, -14, terrainPlains)
  mapLoc(0, -13, terrainPlains)
  mapLoc(-1, -13, terrainPlains)
  mapLoc(-1, -12, terrainPlains)
  mapLoc(-3, -10, terrainPlains)
  mapLoc(-3, -9, terrainPlains)
  mapLoc(-3, -8, terrainPlains)
  mapLoc(-2, -9, terrainPlains)
  mapLoc(-2, -10, terrainPlains)
  mapLoc(-1, -10, terrainPlains)
  mapLoc(-1, -9, terrainPlains)
  mapLoc(0, -9, terrainPlains)
  mapLoc(1, -10, terrainPlains)
  mapLoc(1, -11, terrainPlains)
  mapLoc(1, -12, terrainPlains)
  mapLoc(0, -11, terrainPlains)
  mapLoc(2, -13, terrainPlains)
  mapLoc(2, -12, terrainPlains)
  mapLoc(2, -11, terrainPlains)
  mapLoc(2, -10, terrainPlains)
  mapLoc(3, -10, terrainPlains)
  mapLoc(3, -11, terrainPlains)
  mapLoc(3, -12, terrainPlains)
  mapLoc(3, -13, terrainPlains)
  mapLoc(3, -14, terrainPlains)
  mapLoc(4, -15, terrainPlains)
  mapLoc(4, -14, terrainPlains)
  mapLoc(4, -13, terrainPlains)
  mapLoc(4, -12, terrainPlains)
  mapLoc(5, -12, terrainPlains)
  mapLoc(5, -13, terrainPlains)
  mapLoc(5, -14, terrainPlains)
  mapLoc(5, -15, terrainPlains)
  mapLoc(5, -16, terrainPlains)
  mapLoc(6, -16, terrainPlains)
  mapLoc(7, -17, terrainPlains)
  mapLoc(8, -17, terrainPlains)
  mapLoc(9, -18, terrainPlains)
  mapLoc(10, -18, terrainPlains)
  mapLoc(9, -17, terrainPlains)
  mapLoc(10, -16, terrainPlains)
  mapLoc(9, -16, terrainPlains)
  mapLoc(8, -16, terrainPlains)
  mapLoc(7, -16, terrainPlains)
  mapLoc(7, -15, terrainPlains)
  mapLoc(7, -14, terrainPlains)
  mapLoc(6, -14, terrainPlains)
  mapLoc(6, -13, terrainPlains)
  return map
end
